### ISSUE TITLE
CdBackend backend caused an exception: TypeError: __init__() got an unexpected keyword argument 'images'

### ISSUE THREAD

**Issue by DerNuntius** [antosart/mopidy-cd#15]
Hi,

After installing the Mopidy-Cd extention I tried to play an audio cd and got this error:

`ERROR    2020-06-26 14:54:46,768 [21020:Core-9] mopidy.core.library
  CdBackend backend caused an exception.
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/mopidy/core/library.py", line 17, in _backend_error_handling
    yield
  File "/usr/lib/python3/dist-packages/mopidy/core/library.py", line 217, in lookup
    result = future.get()
  File "/usr/lib/python3/dist-packages/pykka/_threading.py", line 45, in get
    _compat.reraise(*self._data['exc_info'])
  File "/usr/lib/python3/dist-packages/pykka/_compat/__init__.py", line 29, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/pykka/_actor.py", line 193, in _actor_loop
    response = self._handle_receive(envelope.message)
  File "/usr/lib/python3/dist-packages/pykka/_actor.py", line 299, in _handle_receive
    return callee(*message.args, **message.kwargs)
  File "/home/pi/.local/lib/python3.8/site-packages/mopidy_cd/backend.py", line 44, in lookup
    album = CdLibrary._make_album(disc)
  File "/home/pi/.local/lib/python3.8/site-packages/mopidy_cd/backend.py", line 114, in _make_album
    return Album(
  File "/usr/lib/python3/dist-packages/mopidy/models/immutable.py", line 159, in __call__
    instance = super().__call__(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/mopidy/models/immutable.py", line 32, in __init__
    raise TypeError(
TypeError: __init__() got an unexpected keyword argument 'images'
`

Version:
Mopidy-Cd: 0.5.1

**Comment by DerNuntius** [comment]
Turned out that I had v0.5.0 installed on the mopidy user account.

**Comment by MisjaS** [comment]
Hi, I have exactly the same error. installing version 5.1 did not solve the problem though.
any suggestions are welcome I have no idea where to look.

**Comment by abaj8494** [comment]
Receiving the same error. See #19 

Edit: Check the thread now. Fixed by installing from source.
